server:
  port: 8080
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xat.entity
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
spring:
  datasource:
    username: root
    password: xat123
    url: jdbc:mysql://localhost:3306/xattest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html  
    mode: LEGACYHTML5
    
  rabbitmq:
    host: 192.168.8.102
    port: 5672
    username: guest
    password: guest